figure;
plot(var(:,1),var(:,2));
figure;
plot(var(:,1),var(:,3));
output(1,:)=brakings(1,:);output(1,:)=brakings(1,:);figure;
plot(var(:,1),var(:,4));
% figure;
% plot(var(:,1),var(:,5));
% figure;
% plot(var(:,1),var(:,6));
% figure;
% plot(var(:,1),var(:,7));
% figure;
% plot(var(:,1),var(:,8));